force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <label>employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/demo6.cls
public class demo6 {
    public static void totalsalary(){
        list<account> acc = [select id, total_salary__c ,(select id, salary__c from employees__r) from account where createddate = THIS_YEAR];
        if(!acc.isempty()){
            for(account acclist: acc ){
                decimal totalsal = 0;
                for(employee__c emp:acclist.employees__r){
                    totalsal = totalsal + emp.salary__c;
                }
                acclist.total_salary__c = totalsal;
            }
        }
        if(!acc.isempty()){
            update acc;
        }
    }
    

}