force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <label>employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>employees</relationshipLabel>
    <relationshipName>employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/demo7.cls
public class demo7 {
    public static void copyphoneaccount(){
        list<employee__c> emplist = [select id, name,Phone__c, account__r.phone from employee__c ];
        
        if(!emplist.isempty()){
            for(employee__c emp : emplist){
                if(emp.Phone__c == null){
                    emp.Phone__c = emp.account__r.phone;
                }
            }
        }
        if(!emplist.isempty()){
            update emplist;
        }

}
}