force-app/main/default/objects/Car_Rental__c/Car_Rental__c.object-meta.xml
<CustomObject>
    <label>Car Rental</label>
    <nameField>
        <label>Rental Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental__c/fields/Pickup_City__c.field-meta.xml
<CustomField>
    <fullName>Pickup_City__c</fullName>
    <label>Pickup City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car_Rental__c/fields/Pickup_Country__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Country__c</fullName>
    <label>Pickup Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car_Rental__c/fields/Pickup_Time__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Time__c</fullName>
    <label>Pickup Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Car_Rental__c/fields/Return_City__c.field-meta.xml
<CustomField>
    <fullName>Return_City__c</fullName>
    <label>Return City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car_Rental__c/fields/Return_Country__c.field-meta.xml
<CustomField>
    <fullName>Return_Country__c</fullName>
    <label>Return Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car_Rental__c/fields/Return_Time__c.field-meta.xml
<CustomField>
    <fullName>Return_Time__c</fullName>
    <label>Return Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/controller_class.cls
public with sharing class controller_class {
    public list<Car_Rental__c> newList{get;set;}
    
    public controller_class(ApexPages.StandardController controller){
        newList =[select name,Pickup_Country__c,Pickup_City__c,Return_Country__c,Return_City__c,From_Date__c
                 ,To_Date__c,Pickup_Time__c,Return_Time__c from Car_Rental__c];
    }
    
    public PageReference next() {
    	PageReference pg = new PageReference('/apex/Check_email');
        pg.setRedirect(true);
        return pg;
    }
    
    

}