force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <label>Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <formula>Opening_Balance__c  +  Deposit__c  -  Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Sales_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Date__c</fullName>
    <formula>date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/bankUpdate.cls
public class bankUpdate implements database.Batchable<sObject>, database.stateful{
    
    public integer recordCount = 0;
    public database.QueryLocator start(database.BatchableContext bc){
        return database.getQueryLocator([select Id,  Name, Opening_Balance__c,Closing_Balance__c,Sales_Date__c from Bank__c]);
        
    }
    public void execute(database.BatchableContext bc, list<Bank__c> bankk){
        for(Bank__c bk :bankk){
            bk.Deposit__c = 0;
            bk.Charges__c = 0;
            bk.Opening_Balance__c = bk.Closing_Balance__c;
            
        }
        update bankk;
        recordCount = recordCount + bankk.size();
    }
    public void finish(database.BatchableContext bc){
        system.debug('total records'+ recordCount);
    }
    
    
}