force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <formula>Opening_Balance__c  +  Deposit__c  -  Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Sales_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Date__c</fullName>
    <formula>date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/bankUpdateTest.cls
@isTest
public class bankUpdateTest{
    @isTest
    private static void testBtachClass(){
        list<Bank__c> bankList = new list<Bank__c>();
        
        for(integer i=0; i<5; i++){
            bankList.add(
            new Bank__c(name= 'bank'+ i, Opening_Balance__c=1000, Deposit__c=500));
            
        }
        insert bankList;
        
        Test.startTest();
        bankUpdate bankupdation = new bankUpdate();
        id batchid = database.executeBatch(bankupdation, 5);
        Test.stopTest();
        
        list<Bank__c> updateBankList = [select Id,  Name, Opening_Balance__c,Closing_Balance__c,Sales_Date__c from Bank__c];
        system.assertEquals(5, updateBankList.size());
    }

}