force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <formula>Opening_Balance__c  +  Deposit__c  -  Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Sales_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Date__c</fullName>
    <formula>date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/triggerhandler2.cls
public class triggerhandler2 {
    
    public static void bankRecord(list<Bank__c> newlist,map<id,Bank__c> oldmap ){
         
        
         //map<id,Bank__c> bankIdtoMap = new map<id,Bank__c>();
         list<bank__c> bankTobeUpdated = new list<Bank__c>();
        
        set<id> bankid = new set<id>();
  
        

             for(Bank__c bankv : newlist){
                 if(oldmap != null && bankv.Opening_Balance__c != oldmap.get(bankv.id).Opening_Balance__c){
                     //bankIdtoMap.put(bankv.id,bankv);
                     bankid.add(bankv.Id);
                     
             
              }
                
           }
         for(bank__c bkk : [select id,  name, Opening_Balance__c,Closing_Balance__c,Sales_Date__c from Bank__c where name = 'BOI']){
             
            
             if(bkk.Sales_Date__c == system.today()+ 1){
                 
                 bkk.Opening_Balance__c = bkk.Closing_Balance__c;
                 bankTobeUpdated.add(bkk);
             }
            }
        
        if(!bankTobeUpdated.isEmpty()){
            update bankTobeUpdated;
            
            system.debug('bank'+ bankTobeUpdated);
        
        
       
        
      }
}
}